name: dl
channels:
  - conda-forge  # 添加 conda-forge，通常有更全的包
  - defaults
dependencies:
  - python=3.9  # 根据你的项目需要，保留或修改 Python 版本

  # --- 主要依赖 (通常这些就够了) ---
  - streamlit
  - pandas
  - numpy
  - scikit-learn
  - catboost
  - joblib

  # --- 其他可能需要的依赖 (根据你的 app.py 代码添加) ---
  - matplotlib  # 如果你使用了 matplotlib 进行绘图
  - statsmodels # 如果你使用了 statsmodels

  # --- 从 conda 安装 (移除构建版本号) ---
  # 大部分情况下，以下这些依赖会被上面的主要依赖自动安装，所以通常不需要单独列出
  # 如果你确认需要，可以保留，但去掉版本号后面的构建字符串
  - anyio  # 移除 =4.2.0=py39haa95532_0
  - attrs
  - beautifulsoup4
  - certifi
  - click  # streamlit 的依赖，通常不需要单独列出
  - idna
  - importlib_metadata
  - importlib_resources
  - jsonschema
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - lz4-c
  - matplotlib-base # 如果你使用了 matplotlib，保留这个
  - mkl-service
  - mkl_fft
  - mkl_random
  - notebook
  - openjpeg
  - openssl
  - packaging  # 通常会被其他包自动安装
  - pandas
  - pip
  - plotly # 如果你使用了 Plotly
  - prompt_toolkit
  - protobuf # streamlit的依赖
  - pyarrow # streamlit的依赖
  - pycparser
  - pyparsing
  - pyqt
  - python-dateutil
  - pytz
  - pywinpty
  - pyyaml
  - requests
  - rpds-py
  - scipy
  - seaborn # 如果你使用了 seaborn
  - send2trash
  - setuptools
  - six
  - sniffio
  - sqlite
  - terminado
  - tinycss2
  - tomli
  - tornado  # streamlit 的依赖
  - typing_extensions
  - tzdata
  - urllib3
  - websocket-client
  - wheel
  - widgetsnbextension
  - win_inet_pton
  - zlib
  - zstd

  # --- pip 安装 (移除版本号，除非你确实需要特定版本) ---
  - pip:
    - adjusttext
    - airr
    - alabaster
    - altair
    - anndata
    - array-api-compat
    - asttokens
    - autograd
    - autograd-gamma
    - awkward
    - awkward-cpp
    - babel
    - blinker
    - bounded-pool-executor
    - cachetools
    - click # 重复了，conda 部分已经有了
    - cloudpickle
    - comm
    - contourpy
    - cycler
    - debugpy
    - docutils
    - ecos
    - eli5
    - et-xmlfile
    - exceptiongroup
    - executing
    - filelock
    - fonttools
    - formulaic
    - fsspec
    - get-annotations
    - gitdb
    - gitpython
    - h5py
    - igraph
    - imagesize
    - iniconfig
    - intel-openmp
    - interface-meta
    - ipykernel
    - ipython
    - jedi
    - jinja2
    - joblib # 重复
    - jupyter-client #重复
    - jupyter-core   #重复
    - kiwisolver
    - legacy-api-wrap
    - levenshtein
    - lifelines
    - lightgbm
    - llvmlite
    - markdown-it-py
    - markupsafe
    - matplotlib #重复
    - matplotlib-inline
    - mdurl
    - mkl #重复
    - mpmath
    - mudata
    - narwhals
    - natsort
    - networkx
    - numba
    - numexpr
    - numpydoc
    - openpyxl
    - osqp
    - pandas #重复
    - parasail
    - parso
    - patsy
    - pdpbox
    - pillow
    - platformdirs
    - pluggy
    - pooch
    - pqdm
    - prompt-toolkit # 重复
    - protobuf #重复
    - psutil
    - pyarrow #重复
    - pycairo
    - pydeck
    - pygments
    - pynndescent
    - pytest
    - python-graphviz
    - python-igraph
    - python-levenshtein
    - pytoml
    - pywin32
    - pyzmq
    - qdldl
    - rapidfuzz
    - rich
    - scanpy
    - scikit-learn # 重复
    - scikit-survival
    - scirpy
    - session-info
    - setuptools-scm
    - shap
    - slicer
    - smmap
    - snowballstemmer
    - sns
    - sphinx
    - sphinx-rtd-theme
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jquery
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - squarify
    - stack-data # 重复
    - statsmodels #重复
    - stdlib-list
    - streamlit #重复
    - sympy
    - tabulate
    - tbb
    - tenacity
    - texttable
    - threadpoolctl
    - toml #重复
    - torch #如果不用torch, 可以删除
    - torchaudio#如果不用torch, 可以删除
    - torchvision#如果不用torch, 可以删除
    - tornado#重复
    - tqdm
    - traitlets
    - typing-extensions #重复
    - umap-learn
    - watchdog
    - wcwidth
    - wrapt
    - yamlordereddictloader
    - zipp
