name: copd-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9     
  - streamlit
  - pandas
  - numpy
  - scikit-learn
  - catboost
  - joblib
  - matplotlib     
  - statsmodels 
