name: copd-app  # 你可以自定义环境名称
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.19  # 根据你的应用调整 Python 版本
  - streamlit == 1.42.2 
  - pandas ==  2.2.3
  - numpy ==  1.26.4
  - scikit-learn ==   1.5.2
  - catboost == 1.2.7 
  - joblib == 1.4.2  
  - matplotlib ==3.9.0 
  - statsmodels ==  0.14.4    
