name: dl  # 你的环境名称
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # 根据你的需要修改 Python 版本
  - streamlit
  - pandas
  - numpy
  - scikit-learn
  - catboost
  - joblib
  - matplotlib  # 如果你的 app.py 中使用了 matplotlib 进行绘图，则保留
  - statsmodels # 如果你的app.py中使用了, 则保留
